services:

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8003"
    volumes:
      - .:/app
    expose:
      - "8003"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $USER" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: