# Generated by Django 6.0.5 on 2026-06-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('post', models.CharField(max_length=150, verbose_name='должность')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
                ('period', models.DateTimeField(verbose_name='срок')),
                ('status', models.CharField(choices=[('created', 'создана'), ('in_progress', 'выполняется'), ('done', 'закончена')], default='created', max_length=15, verbose_name='статус')),
                ('executor', models.ManyToManyField(blank=True, max_length=150, related_name='task', to='task.employee', verbose_name='исполнитель')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_tasks', to='task.task', verbose_name='ссылка на родительскую задачу')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['period'],
            },
        ),
    ]
